command: [
  "streamlit", 
  "run",
  "home.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: SQL_WAREHOUSE
    valueFrom: "sql_warehouse"
  - name: DEPLOY_MODEL_JOB_ID
    valueFrom: "deploy_model_job"
  - name: BIONEMO_ESM_FINETUNE_JOB_ID
    valueFrom: "bionemo_esm_finetune_job"


