command: [
  "streamlit", 
  "run",
  "home.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: SQL_WAREHOUSE
    valueFrom: "sql_warehouse"
  - name: CORE_CATALOG_NAME
    valueFrom: "core_catalog_name"
  - name: CORE_SCHEMA_NAME
    valueFrom: "core_schema_name"




